// Generated by https://quicktype.io

export interface Afiliado {
  ApeyNom: string;
  Cuil: string;
  Edad: number;
  Estado: number;
  Familiar: string;
  FechaEstado: string;
  FechaNacimiento: string;
  Materno: boolean;
  Numero: string;
  Sexo: string;
  TipoDoc: string;
  Documento: string;
  Voluntario: boolean;
  OrdenVM: null;
}
