// Generated by https://quicktype.io

export class Afiliado {
  ApeyNom: string = '';
  Cuil: string = '';
  Edad: number = 0;
  Estado: number = -1;
  Familiar: string = '';
  FechaEstado: string = '';
  FechaNacimiento: string = '';
  Materno: boolean  = false;
  Numero: string = '';
  Sexo: string = '';
  TipoDoc: string = '';
  Documento: string = '';
  Voluntario: boolean = false;
  OrdenVM: null;
  
  
}
